version: '3'
networks:
  dev_network:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:12-3.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - dev_network
      